name: ProgramCodeConvention

on:
  # Позволяет запускать рабочий процесс вручную из UI GitHub
  workflow_dispatch:
  # Запускает рабочий процесс при каждом пуше в ветку main
  push:
    branches:
      - main
  # Запускает рабочий процесс при создании Pull Request
  pull_request:
    branches:
      - main

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super-Linter (Python Validation)
        uses: super-linter/super-linter@v6 # Использование актуальной версии
        env:
          # Включаем только проверку Python для ускорения
          VALIDATE_PYTHON: true
          # Устанавливаем критический уровень для завершения с ошибкой
          FILTER_REGEX_INCLUDE: |
            .*(\.py)$
